export enum EnvVariables {
  AIRSTRIP_LOG_LEVEL = 'AIRSTRIP_LOG_LEVEL',
  AIRSTRIP_ALLOWED_ORIGINS = 'AIRSTRIP_ALLOWED_ORIGINS',
  AIRSTRIP_FRONTEND_URL = 'AIRSTRIP_FRONTEND_URL',
  AIRSTRIP_PORT = 'AIRSTRIP_PORT',

  AIRSTRIP_JWT_SIGN_ALG = 'AIRSTRIP_JWT_SIGN_ALG',
  AIRSTRIP_JWT_PUBLIC_JWK = 'AIRSTRIP_JWT_PUBLIC_JWK',
  AIRSTRIP_JWT_PRIVATE_JWK = 'AIRSTRIP_JWT_PRIVATE_JWK',

  AIRSTRIP_SQL_LOGGING = 'AIRSTRIP_SQL_LOGGING',
  AIRSTRIP_DB_HOST = 'AIRSTRIP_DB_HOST',
  AIRSTRIP_DB_PORT = 'AIRSTRIP_DB_PORT',
  AIRSTRIP_DB_USER = 'AIRSTRIP_DB_USER',
  AIRSTRIP_DB_PASSWORD = 'AIRSTRIP_DB_PASSWORD',
  AIRSTRIP_DB_NAME = 'AIRSTRIP_DB_NAME',
  AIRSTRIP_DB_SSL_CERT = 'AIRSTRIP_DB_SSL_CERT',

  AIRSTRIP_SMTP_HOST = 'AIRSTRIP_SMTP_HOST',
  AIRSTRIP_SMTP_PORT = 'AIRSTRIP_SMTP_PORT',
  AIRSTRIP_SMTP_USER = 'AIRSTRIP_SMTP_USER',
  AIRSTRIP_SMTP_PASSWORD = 'AIRSTRIP_SMTP_PASSWORD',
  AIRSTRIP_EMAIL_SENDER = 'AIRSTRIP_EMAIL_SENDER',

  AIRSTRIP_INFISICAL_API_URL = 'AIRSTRIP_INFISICAL_API_URL',
  AIRSTRIP_INFISICAL_CLIENT_ID = 'AIRSTRIP_INFISICAL_CLIENT_ID',
  AIRSTRIP_INFISICAL_CLIENT_SECRET = 'AIRSTRIP_INFISICAL_CLIENT_SECRET',
  AIRSTRIP_INFISICAL_PROJECT_ID = 'AIRSTRIP_INFISICAL_PROJECT_ID',
  AIRSTRIP_INFISICAL_PROJECT_ENV = 'AIRSTRIP_INFISICAL_PROJECT_ENV',
}
