services:
  db:
    # image: 'postgres:14'
    image: 'pgvector/pgvector:pg14'
    container_name: 'airstrip-db'
    restart: always
    volumes:
      - ./airstrip-be/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  clickhouse-db:
    image: 'clickhouse/clickhouse-server:latest'
    container_name: 'airstrip-clickhouse-db'
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  fe:
    container_name: 'airstrip-fe'
    build:
      context: ./airstrip-fe
      dockerfile: Dockerfile
    env_file: ./airstrip-fe/.env
    # env_file here is used ONLY by drizzle and clickhouse for db migration purposes.
    # This is not available at build time and therefore not available to compiled app - nextjs bakes the env variables into the build.
    # To change the env vars, update ARG in frontend's Dockerfile.
    environment:
      - AIRSTRIP_DB_HOST=db
      - CLICKHOUSE_HOST=http://clickhouse-db:8123
    ports:
      - '3000:3000'
    depends_on:
      - db
      - clickhouse-db
  be:
    container_name: 'airstrip-be'
    build:
      context: ./airstrip-be
      dockerfile: Dockerfile
    env_file: ./airstrip-be/.env
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - AIRSTRIP_DB_HOST=db
  # Local AWS services
  localstack:
    container_name: 'airstrip-localstack'
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      # - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - 'localstack_data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.localstack:/etc/localstack/init/ready.d' # ready hook
  unstructured:
    container_name: 'airstrip-unstructured'
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - '4322:8000'

volumes:
  pg_data:
    driver: local
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  localstack_data:
    driver: local
