services:
  db:
    image: 'postgres:14'
    container_name: 'airstrip-db'
    restart: always
    volumes:
      - ./airstrip-be/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  fe:
    container_name: 'airstrip-fe'
    build:
      context: ./airstrip-fe
      dockerfile: Dockerfile
    env_file: ./airstrip-fe/.env
    # env_file here is used ONLY by drizzle for db migration purposes.
    # This is not available at build time and therefore not available to compiled app - nextjs bakes the env variables into the build.
    # To change the env vars, update ARG in frontend's Dockerfile.
    environment:
      - AIRSTRIP_DB_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
  be:
    container_name: 'airstrip-be'
    build:
      context: ./airstrip-be
      dockerfile: Dockerfile
    env_file: ./airstrip-be/.env
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - AIRSTRIP_DB_HOST=db

volumes:
  pg_data:
    driver: local
