services:
  db:
    image: "postgres:14"
    container_name: "airstrip-db"
    restart: always
    volumes:
      - ./airstrip-be/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  clickhouse-db:
    image: 'clickhouse/clickhouse-server:latest'
    container_name: 'airstrip-clickhouse-db'
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
volumes:
  pg_data:
    driver: local
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
