services:
  db:
    image: "postgres:14"
    container_name: "airstrip-db"
    restart: always
    volumes:
      - ./airstrip-be/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  flyway:
    image: flyway/flyway
    container_name: "airstrip-be-migration-runner"
    command: -url=jdbc:postgresql://db:5432/airstrip -user=airstrip -password=airstrip -baselineOnMigrate=false -outOfOrder=false -failOnMissingLocations=true -connectRetries=10 migrate
    volumes:
      - ./airstrip-be/migrations:/flyway/sql
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
